# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - go mod tidy
builds:
  - binary: shiori
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
# ! archives is a pro feature
# https://goreleaser.com/customization/archive/?h=archive
# archives:
#   - id: shiori
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- if eq .Os "darwin" }}Darwin{{- else if eq .Os "linux" }}Linux{{- else if eq .Os "windows" }}Windows{{- else }}{{ .Os }}{{ end }}_
#       {{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "arm64" }}aarch64{{- else }}{{ .Arch }}{{ end }}

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    dockerfile: "{{ .Env.DOCKERFILE }}"
    goos: linux
    goarch: amd64
    skip_push: false
    image_templates:
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--builder=orbstack"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - ./

  - use: buildx
    dockerfile: "{{ .Env.DOCKERFILE }}"
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--builder=orbstack"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - ./

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - name_template: "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:latest-amd64"
      - "{{ .Env.DOCKER_REG }}/{{ .Env.GIT_USER }}/{{ .ProjectName }}:latest-arm64v8"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
