FROM docker.io/golang:1.19-alpine3.18
ARG TARGETARCH
# LABEL org.opencontainers.image.source https://github.com/go-shiori/shiori
COPY etc /etc
COPY binaries/shiori_linux_$TARGETARCH/shiori /usr/bin/shiori
USER shiori
WORKDIR /shiori
EXPOSE 8080
ENV SHIORI_DIR=/shiori
ENTRYPOINT ["/usr/bin/shiori"]
CMD ["serve"]
