name: "GoReleaser - ghcr.io"

on: workflow_call

permissions:
  contents: write

jobs:
  # use goreleaser to cross-compile go binaries and add them to GitHub release
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "pythoninthegrass/shiori"
      - name: Run GoReleaser
        uses:  goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
